import type { LucideIcon } from "lucide-react"
import {
  Activity,
  BarChart3,
  Bell,
  Bot,
  BookOpen,
  CheckSquare,
  Cloud,
  Coins,
  Cpu,
  Database,
  Eye,
  FileText,
  FolderOpen,
  Gauge,
  HardDrive,
  Key,
  KeyRound,
  LayoutDashboard,
  Lock,
  Package,
  PanelLeft,
  PanelLeftClose,
  Plug,
  Route,
  Server,
  Settings,
  Shield,
  Sparkles,
  Tags,
  Ticket,
  UserCheck,
  UserCog,
  Users,
} from "lucide-react"

// Icon registry for sidebar navigation. We keep icons in client components
// and reference them by string name in navigation config to avoid
// non-serializable values being passed from Server to Client Components.
export const navIconMap = {
  layoutDashboard: LayoutDashboard,
  route: Route,
  server: Server,
  plug: Plug,
  cpu: Cpu,
  key: Key,
  coins: Coins,
  activity: Activity,
  fileText: FileText,
  users: Users,
  shield: Shield,
  lock: Lock,
  database: Database,
  settings: Settings,
  barChart3: BarChart3,
  bell: Bell,
  userCog: UserCog,
  panelLeft: PanelLeft,
  panelLeftClose: PanelLeftClose,
  bot: Bot,
  // Storage navigation icons
  folderOpen: FolderOpen,
  hardDrive: HardDrive,
  // Admin navigation icons
  eye: Eye,
  sparkles: Sparkles,
  checkSquare: CheckSquare,
  tags: Tags,
  bookOpen: BookOpen,
  userCheck: UserCheck,
  keyRound: KeyRound,
  gauge: Gauge,
  ticket: Ticket,
  cloud: Cloud,
  package: Package,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof navIconMap

export const defaultNavIcon: LucideIcon = LayoutDashboard
