"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Loader2, Sparkles, Save } from "lucide-react";

import { useI18n } from "@/lib/i18n-context";
import { useProviderRules } from "@/lib/swr/use-provider-rules";

export default function MappingsPage() {
  const { t } = useI18n();
  const { metadataList, generateMapping } = useProviderRules();
  
  const [providerSlug, setProviderSlug] = useState("");
  const [serviceType, setServiceType] = useState("audio");
  const [schemaJson, setSchemaJson] = useState("");
  
  const [inputMap, setInputMap] = useState("");
  const [outputMap, setOutputMap] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = async () => {
    if (!providerSlug || !schemaJson) {
      toast.error("Please select a provider and provide a schema");
      return;
    }
    
    setIsGenerating(true);
    try {
      const res = await generateMapping.trigger({
        provider_slug: providerSlug,
        service_type: serviceType,
        unified_schema_json: schemaJson
      });
      
      setInputMap(JSON.stringify(res.input_map, null, 2));
      setOutputMap(JSON.stringify(res.output_map, null, 2));
      toast.success(t("system.agents.mappings.gen_success"));
    } catch (err) {
      toast.error(t("system.agents.mappings.gen_error"));
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto py-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">{t("system.agents.mappings.title")}</h1>
        <p className="text-muted-foreground">{t("system.agents.mappings.subtitle")}</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="md:col-span-1">
          <CardHeader>
            <CardTitle>{t("system.agents.mappings.generate")}</CardTitle>
            <CardDescription>Configure parameters for AI generation</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label>{t("system.agents.mappings.provider")}</Label>
              <Select value={providerSlug} onValueChange={setProviderSlug}>
                <SelectTrigger>
                  <SelectValue placeholder="Select Provider" />
                </SelectTrigger>
                <SelectContent>
                  {metadataList.map((m) => (
                    <SelectItem key={m.id} value={m.provider_slug}>
                      {m.name || m.provider_slug}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>{t("system.agents.mappings.service_type")}</Label>
              <Select value={serviceType} onValueChange={setServiceType}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="audio">Audio (TTS)</SelectItem>
                  <SelectItem value="video">Video Generation</SelectItem>
                  <SelectItem value="image">Image Generation</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>{t("system.agents.mappings.unified_schema")}</Label>
              <Textarea 
                value={schemaJson} 
                onChange={(e) => setSchemaJson(e.target.value)}
                placeholder='{"text": "string", "voice": "string"}'
                className="font-mono text-xs h-48"
              />
            </div>

            <Button 
              className="w-full" 
              onClick={handleGenerate} 
              disabled={isGenerating}
            >
              {isGenerating ? (
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              ) : (
                <Sparkles className="w-4 h-4 mr-2" />
              )}
              {isGenerating ? t("system.agents.mappings.generating") : t("system.agents.mappings.generate")}
            </Button>
          </CardContent>
        </Card>

        <Card className="md:col-span-2">
          <CardHeader>
            <CardTitle>Generated Mapping Rules</CardTitle>
            <CardDescription>Preview and edit the mapping rules generated by AI</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-2">
              <Label>{t("system.agents.mappings.input_map")}</Label>
              <Textarea 
                value={inputMap} 
                onChange={(e) => setInputMap(e.target.value)}
                className="font-mono text-xs h-64"
                placeholder="{}"
              />
            </div>

            <div className="space-y-2">
              <Label>{t("system.agents.mappings.output_map")}</Label>
              <Textarea 
                value={outputMap} 
                onChange={(e) => setOutputMap(e.target.value)}
                className="font-mono text-xs h-48"
                placeholder="{}"
              />
            </div>

            <div className="flex justify-end">
              <Button disabled={!inputMap}>
                <Save className="w-4 h-4 mr-2" />
                Save Mapping
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
